const fs = require("fs"); let c = fs.readFileSync("src/modules/randevu/infrastructure/repositories/SupabaseAppointmentRepository.ts", "utf8"); 
c = c.replace(/booking_token: appointmentData.bookingToken/g, "booking_token: appointmentData.bookingToken,\n      calendar_id: appointmentData.calendarId");
c = c.replace(/async findAvailableHours\(date: string, serviceId: string\): Promise<string\[\]> {/, "async findAvailableHours(date: string, serviceId: string, calendarId?: string): Promise<string[]> {");
c = c.replace(/const \{ data, error \} = await supabase\n      .from\(\x27appointments\x27\)\n      .select\(\x27date\x27\)\n      .like\(\x27date\x27, `\$\{date\}%`\)\n      .in\(\x27status\x27, \[AppointmentStatus.Pending, AppointmentStatus.Approved\]\);/g, `let query = supabase.from("appointments").select("date").like("date", \\\`\${date}%\\\`).in("status", [AppointmentStatus.Pending, AppointmentStatus.Approved]);\n    if (calendarId) query = query.eq("calendar_id", calendarId);\n    const { data, error } = await query;`);
c = c.replace(/async getAppointmentsByDate\(date: string\): Promise<Appointment\[\]> {/, "async getAppointmentsByDate(date: string, calendarId?: string): Promise<Appointment[]> {");
c = c.replace(/const \{ data: appointments, error \} = await supabase\n      .from\(\x27appointments\x27\)\n      .select\(\x27\*\x27\)\n      .like\(\x27date\x27, `\$\{date\}%`\)\n      .in\(\x27status\x27, \[AppointmentStatus.Pending, AppointmentStatus.Approved\]\)\n      .order\(\x27created_at\x27, \{ ascending: true \}\);/g, `let query = supabase.from("appointments").select("*").like("date", \\\`\${date}%\\\`).in("status", [AppointmentStatus.Pending, AppointmentStatus.Approved]).order("created_at", { ascending: true });\n    if (calendarId) query = query.eq("calendar_id", calendarId);\n    const { data: appointments, error } = await query;`);
c = c.replace(/subscribeToAppointments\(\n    date: string,\n    callback: \(appointments: Appointment\[\]\) => void\n  \): \(\) => void {/g, "subscribeToAppointments(\n    date: string,\n    calendarId: string | undefined,\n    callback: (appointments: Appointment[]) => void\n  ): () => void {");
c = c.replace(/const fresh = await this.getAppointmentsByDate\(date\);/g, "const fresh = await this.getAppointmentsByDate(date, calendarId);");
fs.writeFileSync("src/modules/randevu/infrastructure/repositories/SupabaseAppointmentRepository.ts", c, "utf8"); console.log("OK");
