/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: '#0B0F19',
        surface: '#161B26',
        primary: '#00F2FE',
        secondary: '#4FACFE',
        'text-primary': '#FFFFFF',
        'text-secondary': '#94A3B8',
        tertiary: '#7000ff',
        glassBorder: 'rgba(255, 255, 255, 0.1)',
        glassBg: 'rgba(255, 255, 255, 0.03)',
        'on-secondary-fixed-variant': '#74009f',
        'inverse-surface': '#e5e2e3',
        'primary-container': '#00f0ff',
        'surface-bright': '#3a393a',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#d1bcff',
        'outline': '#849495',
        'inverse-on-surface': '#313031',
        'surface-container-lowest': '#0e0e0f',
        'secondary-fixed': '#f8d8ff',
        'on-tertiary-fixed': '#23005b',
        'on-tertiary-container': '#7213ff',
        'primary-fixed': '#7df4ff',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#5700c9',
        'on-background': '#e5e2e3',
        'inverse-primary': '#006970',
        'on-surface-variant': '#b9cacb',
        'tertiary-fixed': '#e9ddff',
        'secondary-container': '#b600f8',
        'on-secondary-fixed': '#320047',
        'secondary-fixed-dim': '#ebb2ff',
        'error': '#ffb4ab',
        'on-surface': '#e5e2e3',
        'surface-dim': '#131314',
        'on-error': '#690005',
        'surface-variant': '#353436',
        'surface-container-low': '#1c1b1c',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-high': '#2a2a2b',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-container': '#006970',
        'outline-variant': '#3b494b',
        'on-secondary': '#520072',
        'tertiary-container': '#e1d2ff',
        'surface-container-highest': '#353436',
        'surface-tint': '#00dbe9',
        'on-primary': '#00363a',
        'surface-container': '#201f20',
        'on-primary-fixed': '#002022',
        'on-tertiary': '#3c0090',
        'on-secondary-container': '#fff6fc'
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        geist: ['Geist', 'monospace'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif']
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }]
      },
      borderRadius: {
        'bento': '24px',
        'glass': '16px',
        'small': '12px',
        'large': '20px',
      },
      spacing: {
        'stack-sm': '8px',
        'glass-padding': '20px',
        'bento-gap': '12px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'container-margin': '20px'
      }
    },
  },
  plugins: [],
}
