import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './dashboardTheme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  // --- HERO ------------------------------------------------------------
  hero: {
    backgroundColor: '#38BDF8',
    paddingHorizontal: 20,
    paddingBottom: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  heroAvatarOuter: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAvatarHalo: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(23, 21, 26, 0.55)',
  },
  heroAvatarWrapper: {
    width: 46,
    height: 46,
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#F6F1EC',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  heroAvatarImage: {
    width: '100%',
    height: '100%',
  },
  onlineDot: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    backgroundColor: COLORS.tertiaryContainer,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#38BDF8',
  },
  heroIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(23, 21, 26, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: 6,
    right: 7,
    width: 9,
    height: 9,
    backgroundColor: '#EF4444',
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: '#38BDF8',
  },
  heroGreeting: {
    color: '#FEF08A',
    fontSize: 14,
    fontWeight: '700',
    fontStyle: 'italic',
    marginBottom: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  heroName: {
    color: '#FDE047',
    fontSize: 26,
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'AvenirNext-Heavy' : 'sans-serif-medium',
    letterSpacing: 0.5,
    marginBottom: 18,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  heroAiCard: {
    backgroundColor: '#17151A',
    borderRadius: 24,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  heroAiIconWrapper: {
    width: 68,
    height: 68,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 122, 89, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  heroAiTexts: {
    flex: 1,
  },
  heroAiTitle: {
    color: '#F6F1EC',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  heroAiSubtitle: {
    color: '#A79E96',
    fontSize: 12,
    fontWeight: '500',
  },

  // --- BODY --------------------------------------------------------------
  body: {
    paddingHorizontal: 16,
    paddingTop: 20,
  },

  // Kart temeli — CustomGlassCard bunu her zaman baz alır.
  glassCard: {
    backgroundColor: 'rgba(42, 38, 49, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255, 247, 240, 0.06)',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 6,
  },

  financeGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  financeCard: {
    flex: 1,
    padding: 16,
  },
  financeHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  financeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
  },
  financeBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  financeValueText: {
    color: COLORS.onSurface,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 12,
  },
  financeValueCurrency: {
    color: COLORS.onSurfaceVariant,
    fontSize: 13,
    fontWeight: '500',
  },
  barChartContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 36,
    gap: 4,
  },
  barChartBar: {
    flex: 1,
    borderRadius: 3,
    minHeight: 4,
  },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  sectionTitle: { color: COLORS.onSurfaceVariant, fontSize: 12, fontWeight: '600', letterSpacing: 0.84 },
  seeAllBtn: {
    color: '#38BDF8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },

  apptList: {
    gap: 10,
    marginBottom: 20,
  },
  apptListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  apptListDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
  },
  apptListTime: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: '700',
    width: 44,
  },
  apptListTitle: {
    flex: 1,
    color: COLORS.onSurface,
    fontSize: 13,
    fontWeight: '600',
  },

  socialCard: {
    padding: 16,
    marginBottom: 20,
  },
  socialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  socialProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  socialAvatar: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(34, 181, 115, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialUsername: {
    color: COLORS.onSurface,
    fontSize: 14,
    fontWeight: '700',
  },
  liveBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: 'rgba(56, 189, 248, 0.15)',
  },
  liveBadgeText: {
    color: '#38BDF8',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  socialStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  statsLabelText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 11,
    marginBottom: 6,
  },
  followerRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  followerValue: {
    color: COLORS.onSurface,
    fontSize: 24,
    fontWeight: '800',
  },
  followerTrend: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  followerTrendText: {
    color: COLORS.tertiaryFixed,
    fontSize: 11,
    fontWeight: '700',
  },
  trendBarBg: {
    width: 90,
    height: 8,
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: 6,
    overflow: 'hidden',
  },
  trendBarFill: {
    height: '100%',
    borderRadius: 6,
  },

  invoiceCard: {
    padding: 16,
    marginBottom: 20,
  },
  invoiceCardHeader: {
    fontSize: 11,
    color: '#F59E0B',
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 14,
  },
  invoiceContentRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
  },
  invoiceImageWrapper: {
    width: 64,
    height: 82,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.2)',
  },
  invoiceImage: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  invoiceDetails: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'space-between',
  },
  invoiceDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  invoiceDetailLabel: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    flexShrink: 0,
    marginRight: 8,
  },
  invoiceDetailValue: {
    color: COLORS.onSurface,
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
    minWidth: 0,
    textAlign: 'right',
  },
  invoiceBtn: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  invoiceBtnText: {
    color: '#F59E0B',
    fontWeight: '700',
    fontSize: 13,
  },

  activitiesContainer: {
    gap: 10,
    marginBottom: 20,
  },
  activityCard: {
    flexDirection: 'row',
    padding: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(42, 38, 49, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    gap: 14,
    alignItems: 'center',
  },
  activityAvatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
  },
  activityAvatarWrap: {
    position: 'relative',
  },
  platformBadge: {
    position: 'absolute',
    bottom: -3,
    right: -3,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.surface,
  },
  activityBody: {
    flex: 1,
  },
  activityTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 2,
  },
  activityName: {
    color: COLORS.onSurface,
    fontSize: 13,
    fontWeight: '700',
  },
  activityTime: {
    color: COLORS.onSurfaceVariant,
    fontSize: 10,
    fontWeight: '500',
    opacity: 0.7,
  },
  activityMessage: {
    color: 'rgba(167, 158, 150, 0.9)',
    fontSize: 12,
    marginBottom: 8,
  },
  activityTagsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  activityTag: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
  },
  activityTagText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  activityArrow: {
    opacity: 0.4,
  },
  emptyText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    textAlign: 'center',
    padding: 16,
  },

  paymentsScroll: {
    gap: 12,
    paddingBottom: 20,
    paddingRight: 4,
  },
  paymentCard: {
    width: 190,
    padding: 16,
  },
  paymentDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  paymentDateText: {
    fontSize: 10,
    fontWeight: '700',
  },
  paymentTitle: {
    color: COLORS.onSurface,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  paymentBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  paymentAmount: {
    color: COLORS.onSurface,
    fontSize: 17,
    fontWeight: '800',
  },
  paymentCurrency: {
    fontSize: 11,
    fontWeight: '700',
    opacity: 0.6,
  },
  paymentMoreBtn: {
    padding: 4,
  },
});
